# Generated by Django 3.2.6 on 2022-01-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultgoals',
            name='user',
        ),
        migrations.DeleteModel(
            name='DefaultActivites',
        ),
        migrations.DeleteModel(
            name='DefaultGoals',
        ),
    ]
