# Generated by Django 3.2.6 on 2021-12-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Activity Type:(e.g- yoga , dance )'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Time you want to achieve:(in hours)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='enddate',
            field=models.DateField(verbose_name='End Date (in yyyy-mm-dd format)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='startdate',
            field=models.DateField(verbose_name='Start Date (in yyyy-mm-dd format)'),
        ),
    ]
