# Generated by Django 3.2.6 on 2021-12-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211218_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='hourscompleted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
