# Generated by Django 3.2.6 on 2022-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_goal_hourscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Activity Type (e.g- yoga , dance )'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Time goal you want to complete (in hours)'),
        ),
    ]
