# Generated by Django 3.2.6 on 2022-01-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220112_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
