# Generated by Django 3.2.6 on 2022-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_defaultactivites_defaultgoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultgoals',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
