# Generated by Django 3.2.6 on 2022-01-16 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_defaultgoals_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultGoals',
            new_name='goals',
        ),
    ]
