# Generated by Django 3.2.6 on 2022-01-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_defaultactivites_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activitylog',
        ),
    ]
