# Generated by Django 3.2.6 on 2022-01-16 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_delete_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultactivites',
            unique_together={('name', 'user')},
        ),
    ]
