# Generated by Django 3.2.6 on 2022-01-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
