# Generated by Django 3.2.6 on 2022-01-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_activitylog_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
