# Generated by Django 3.2.6 on 2022-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_activitylog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultactivites',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Activity Name:'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Goal Name:'),
        ),
    ]
