# Generated by Django 3.2.6 on 2022-01-20 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_activitylog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 20)),
        ),
    ]
